### ISSUE TITLE
Doesn't delete apps it has pushed

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/pat#109]
![image](https://cloud.githubusercontent.com/assets/108/3785534/d438114a-19c5-11e4-98a5-ba839e73326a.png)

Is it correct behaviour to create apps and not delete them?

**Comment by drnic** [comment]
The command in the image for flushing out pat apps:

```
cf apps | grep pats | awk '{ print $1 }' | xargs -L 1 cf delete -f
```

**Comment by anEXPer** [comment]
The alternative we've used in cleaning up after PAT is to create and target a space specifically for PAT, then delete that space after the run. This has the advantage of deleting routes, too.

**Comment by drnic** [comment]
Nice tip!

**Comment by anEXPer** [comment]
I just accepted story https://www.pivotaltracker.com/story/show/79121472, which fixes this issue. There is now a delete workload that can be run each iteration, allowing long-running experiments and generally cleaning up after app pushes, though it doesn't handle routes, which will become an issue if experiments are _very_ long running.

Or, potentially, using the new app manifest feature should allow us to bind all the apps to the same route, thus avoiding a proliferation of random hostnames.

I don't know if this delete works with apps pushed with the REST push, because I have never successfully used that feature.
